'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { Layout } from "antd";

import ThemeProvider from "./components/ThemeContext";
import Navbar from "./components/Navbar";
import FooterCompo from "./components/FooterCompo";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Admin dashboard nextjs antd",
//   description: "Generated by create next app",
// };

const { Header, Content, Footer } = Layout;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ThemeProvider>
          <Layout>
            <Navbar />
            <main className='flex flex-col min-h-screen'>
              <Content>
                {children}
              </Content>
            </main>
            <FooterCompo />
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
